ALTER TABLE `AuditEvent`
    MODIFY `eventType` ENUM('ACTIVATE', 'REFRESH', 'REVOKE', 'REBIND', 'REBIND_DENIED', 'ADMIN_CREATE', 'ADMIN_UPDATE', 'ADMIN_REVOKE', 'INSTALLATION_BLOCKED', 'INSTALLATION_UNBLOCKED', 'INSTALLATION_RELEASED', 'LICENSE_EXPIRED') NOT NULL;
